on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  terraform:
    name: "Terraform Plan for PR"
    runs-on: ubuntu-latest
    steps:
      # Use sparse checkout to only select files in a defined workspace
      # Turning off cone mode ensures that files in the project root are not included during checkout
      # checkout pattern - https://github.com/actions/checkout/issues/483#issuecomment-1756354321
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_call.head_sha }}
          repository: ${{ github.repository }}
          sparse-checkout: ${{ vars.TF_WORKING_DIR }}
          sparse-checkout-cone-mode: false
      - name: Move files to root
        id: plan
        run: |
            mv ${{ vars.TF_WORKING_DIR }}/* .
            rm -rf ${{ vars.TF_WORKING_DIR }}
            ls -lah
      - name: Set AWS context
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-iam-role }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.aws-region }}
          mask-aws-account-id: true
      - name: Setup Terraform ${{ vars.TF_VERSION }} for ${{ vars.ENV }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}
      - name: Terraform Plan for ${{ vars.ENV }}
        run: |
          terraform init -backend-config=${{ vars.TF_BACKEND_CONFIG_FILE }}
          terraform plan -no-color -var-file=${{ vars.TF_VARS_FILE }} -out=.tfplanfile
      - name: Post Terraform plan comment
        if: github.ref != 'refs/heads/main'
        uses: borchero/terraform-plan-comment@v1
        with:
          token: ${{ github.token }}
          planfile: ".tfplanfile"